### ISSUE TITLE
local_ip is not necessarily external ip

### ISSUE THREAD

**Issue by fabianfreyer** [thkl/homebridge-homematic#500]
e.g. when running in a docker, the `local_ip` is in the docker range:

```
[1/23/2020, 3:19:39 AM] [HomeMatic CCU] local ip used : 172.19.0.2. you may change that with local_ip parameter in config
```
However, since docker proxies the ports, that address is not available externally. Specifying the external ip as `local_ip` results in an error binding, as that interface is not available in the container namespace:

```
homebridge_1  | [1/23/2020, 3:18:41 AM] [HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
homebridge_1  | [1/23/2020, 3:18:41 AM] Error: listen EADDRNOTAVAIL: address not available [redacted]:9090
homebridge_1  |     at Server.setupListenHandle [as _listen2] (net.js:1292:21)
homebridge_1  |     at listenInCluster (net.js:1357:12)
homebridge_1  |     at doListen (net.js:1496:7)
homebridge_1  |     at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

Please split up `local_ip` to be able to separately specify the bind address and the external address.

**Comment by thkl** [comment]
i am not getting this. The local_ip parameter will do exact this. You are able to specify an ip address the plugin event server will listen to. What is the bind_ip for ?

**Comment by dkrizic** [comment]
I am not using Docker, but Kubernetes. You must run Homebridge in hostNetworking mode so does not bind to the interface of docker, but directly on the host interface. In Kubernetes it looks like this:

```
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      run: homebridge
    name: homebridge
    namespace: homebridge2
  spec:
    ports:
    - name: ui
      nodePort: 31240
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      run: homebridge
    sessionAffinity: None
    type: NodePort
```

and the deployment

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "14"
  generation: 20
  labels:
    run: homebridge
  name: homebridge
  namespace: homebridge2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: homebridge
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: homebridge
    spec:
      containers:
      - env:
        - name: HOMEBRIDGE_CONFIG_UI
          value: "1"
        - name: TZ
          value: Europe/Berlin
        - name: PACKAGES
          value: ffmpeg
        - name: TERMINATE_ON_ERROR
          value: "1"
        image: oznu/homebridge:debian
        imagePullPolicy: Always
        name: homebridge
        ports:
        - containerPort: 51826
          hostPort: 51826
          name: homebridge
          protocol: TCP
        - containerPort: 8080
          hostPort: 8080
          name: ui
          protocol: TCP
        - containerPort: 10000
          hostPort: 10000
          name: cam0
          protocol: TCP
        - containerPort: 31101
          hostPort: 31101
          name: homematic1
          protocol: TCP
        - containerPort: 31102
          hostPort: 31102
          name: homematic2
          protocol: TCP
        resources:
          limits:
            cpu: 3500m
          requests:
            cpu: "2"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /homebridge
          name: homebridge-config
        - mountPath: /root
          name: homebridge-root
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - command:
        - sh
        - -c
        - sed -e "s/LOCAL_IP/$(hostname -i)/g" </original/config.json >/homebridge/config.json;
          cp /original/package.json /homebridge/
        - sudo chown -R 911:911 "/root/.npm"
        image: busybox
        imagePullPolicy: Always
        name: homebridge-prepare
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /original/config.json
          name: homebridge-config-json
          subPath: config.json
        - mountPath: /original/package.json
          name: homebridge-config-json
          subPath: package.json
        - mountPath: /homebridge
          name: homebridge-config
      nodeSelector:
        kubernetes.io/arch: arm64
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: homebridge
        name: homebridge-config-json
      - name: homebridge-config
        persistentVolumeClaim:
          claimName: homebridge
      - name: homebridge-root
        persistentVolumeClaim:
          claimName: homebridge-root
```

The config.json contains

```
            "local_port":31100,
            "local_ip":"LOCAL_IP",
```

In summary homebridge is available on hostPort 31100. The LOCAL_IP depends on the current node where this it currently runs, therefore a it is replaced in an initContainer at startup time.
